version: '3'
services:
  db:
    image: library/postgres:9.3
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuserpwd
  web:
    environment:
      RAILS_ENV: development
      LAUNCHY_DRY_RUN: 'true'
      BROWSER: /dev/null
    ports:
      - '3000:3000'
    entrypoint: [/rails_project/docker-entry.sh]
    build: .
    command: rails s -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/rails_project
    links:
      - db
